// Comparative benchmark: VortexRdfStore (JS/WASM) config variants vs. rdf-stores.js
// and oxigraph. Emits dashboard-shaped JSON consumed by
// scripts/render_bench_dashboard.py (the JavaScript tab of the GitHub Pages dashboard).
//
// Run (after `npm run build` to produce pkg/web):
//   npm run bench                         # full rdf-stores-scale run (D=128 — heavy)
//   BENCH_DIM=25 BENCH_DIM_QUADS=10 MUT_BATCH=2000 npm run bench   # quick local check
//
// Methodology mirrors rdf-stores.js's perf harness: a synthetic dataset generated by
// nested loops over a `dimension`, exercised across the six routing shapes the Rust
// dashboard also uses (S/P/O/PO/G/SPOG) plus fully-bound and full-scan.
//
// This file is the ORCHESTRATOR only — it spawns one child process per adapter
// (compare.worker.ts) and collects the results. Adapters used to share this process,
// but that let earlier adapters' peak WASM/JS memory contaminate later ones (observed:
// oxigraph's own wasm module trapping with `unreachable` only after several other
// multi-million-quad stores had already grown and been freed in the same process — it
// runs clean in isolation with the exact same dataset). Process-per-adapter also means
// a crash in one adapter loses only that adapter's rows, not the whole run, and gives
// each adapter a trustworthy, uncontaminated peak-RSS reading (see shared.ts's
// `peakRssMb`).
//
// Uses tinybench + @codspeed/tinybench-plugin — the same harness rdf-stores.js uses.
// `withCodSpeed` is a no-op when not run under the CodSpeed action, so this produces
// plain wall-clock results and is NEVER uploaded to CodSpeed (no JS CodSpeed workflow
// exists; this is never run via CodSpeedHQ/action). CodSpeed stays Rust-only.

import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { cpus, tmpdir } from 'node:os';
import { writeFileSync, readFileSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';

import { ADAPTERS, MUT_ADAPTERS, D, DQ, MUT_BATCH, QUERY_OPTS, HEAVY_OPTS, FULL_SCAN_OPTS, type Row } from './shared.js';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const workerPath = resolve(here, 'compare.worker.ts');
const tsxBin = resolve(here, '..', 'node_modules', '.bin', 'tsx');

const OUT = resolve(here, process.env.BENCH_OUT ?? 'results.json');

interface MemoryRow { slug: string; label: string; role: string; peakRssMb: number | null }
interface WorkerOutput { rows: Row[]; peakRssMb: number | null }

function runWorker(slug: string, role: 'query' | 'mutate'): WorkerOutput | null {
    const outFile = join(tmpdir(), `vortex-bench-${slug}-${role}-${process.pid}.json`);
    const res = spawnSync(tsxBin, ['--expose-gc', '--max-old-space-size=8192', workerPath, slug, role, outFile], {
        stdio: 'inherit',
        env: process.env,
    });
    try {
        if (res.status !== 0) {
            console.error(`\n[${slug}/${role}] worker exited ${res.status} — skipping; other adapters still run.`);
            return null;
        }
        return JSON.parse(readFileSync(outFile, 'utf8')) as WorkerOutput;
    } catch (e) {
        console.error(`[${slug}/${role}] failed to read worker output:`, e);
        return null;
    } finally {
        rmSync(outFile, { force: true });
    }
}

async function main(): Promise<void> {
    console.log(`Dataset shape: triples D=${D} (${(D ** 3).toLocaleString()} quads), quads Dq=${DQ} (${(DQ ** 4).toLocaleString()} quads)…`);

    const results: Row[] = [];
    const memory: MemoryRow[] = [];

    for (const a of ADAPTERS) {
        const out = runWorker(a.slug, 'query');
        if (!out) continue;
        results.push(...out.rows);
        memory.push({ slug: a.slug, label: a.label, role: 'query', peakRssMb: out.peakRssMb });
        console.log(`[${a.label}] peak RSS: ${out.peakRssMb ?? 'unknown'} MB`);
    }

    for (const a of MUT_ADAPTERS) {
        const out = runWorker(a.slug, 'mutate');
        if (!out) continue;
        results.push(...out.rows);
        memory.push({ slug: a.slug, label: a.label, role: 'mutate', peakRssMb: out.peakRssMb });
        console.log(`[${a.label}] peak RSS: ${out.peakRssMb ?? 'unknown'} MB`);
    }

    const config = {
        triplesCount: D ** 3,
        quadsCount: DQ ** 4,
        mutBatch: MUT_BATCH,
        queryIterations: QUERY_OPTS.iterations,
        heavyIterations: HEAVY_OPTS.iterations,
        fullScanIterations: FULL_SCAN_OPTS.iterations,
    };

    writeFileSync(OUT, JSON.stringify({ provenance: provenance(), results, memory, config }, null, 2));
    console.log(`\nWrote ${results.length} benchmark rows, ${memory.length} memory readings → ${OUT}`);
}

function depVersion(pkg: string): string {
    // Some packages' `exports` block a subpath import of package.json; fall back to
    // reading the installed manifest directly.
    try { return require(`${pkg}/package.json`).version as string; } catch { /* try fs */ }
    try {
        const path = resolve(here, '..', 'node_modules', pkg, 'package.json');
        return JSON.parse(readFileSync(path, 'utf8')).version as string;
    } catch { return '?'; }
}

function provenance(): string {
    const date = new Date().toISOString().slice(0, 10);
    const cpu = cpus()[0]?.model ?? 'unknown CPU';
    return (
        `Measured ${date} · node ${process.version} · ${cpu}, ${cpus().length} threads · ` +
        `triples D=${D} (${(D ** 3).toLocaleString()} quads), quads Dq=${DQ} (${(DQ ** 4).toLocaleString()} quads), ` +
        `MUT_BATCH=${MUT_BATCH.toLocaleString()} · tinybench ${depVersion('tinybench')}, wall-clock · ` +
        `vortex-rdf-store ${require('../package.json').version}, rdf-stores ${depVersion('rdf-stores')}, oxigraph ${depVersion('oxigraph')} · ` +
        `one adapter per process, isolated`
    );
}

main().catch((e) => { console.error(e); process.exit(1); });
